window["distri/util:master"]({
  "source": {
    "LICENSE": {
      "path": "LICENSE",
      "mode": "100644",
      "content": "The MIT License (MIT)\n\nCopyright (c) 2014 \n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.",
      "type": "blob"
    },
    "README.md": {
      "path": "README.md",
      "mode": "100644",
      "content": "util\n====\n\nSmall utility methods for JS\n",
      "type": "blob"
    },
    "main.coffee.md": {
      "path": "main.coffee.md",
      "mode": "100644",
      "content": "Util\n====\n\n    module.exports =\n      approach: (current, target, amount) ->\n        (target - current).clamp(-amount, amount) + current\n\nApply a stylesheet idempotently.\n\n      applyStylesheet: (style, id=\"primary\") ->\n        styleNode = document.createElement(\"style\")\n        styleNode.innerHTML = style\n        styleNode.id = id\n\n        if previousStyleNode = document.head.querySelector(\"style##{id}\")\n          previousStyleNode.parentNode.removeChild(prevousStyleNode)\n\n        document.head.appendChild(styleNode)\n\n      defaults: (target, objects...) ->\n        for object in objects\n          for name of object\n            unless target.hasOwnProperty(name)\n              target[name] = object[name]\n\n        return target\n\n      extend: (target, sources...) ->\n        for source in sources\n          for name of source\n            target[name] = source[name]\n\n        return target\n",
      "type": "blob"
    },
    "pixie.cson": {
      "path": "pixie.cson",
      "mode": "100644",
      "content": "version: \"0.1.0\"\n",
      "type": "blob"
    }
  },
  "distribution": {
    "main": {
      "path": "main",
      "content": "(function() {\n  var __slice = [].slice;\n\n  module.exports = {\n    approach: function(current, target, amount) {\n      return (target - current).clamp(-amount, amount) + current;\n    },\n    applyStylesheet: function(style, id) {\n      var previousStyleNode, styleNode;\n      if (id == null) {\n        id = \"primary\";\n      }\n      styleNode = document.createElement(\"style\");\n      styleNode.innerHTML = style;\n      styleNode.id = id;\n      if (previousStyleNode = document.head.querySelector(\"style#\" + id)) {\n        previousStyleNode.parentNode.removeChild(prevousStyleNode);\n      }\n      return document.head.appendChild(styleNode);\n    },\n    defaults: function() {\n      var name, object, objects, target, _i, _len;\n      target = arguments[0], objects = 2 <= arguments.length ? __slice.call(arguments, 1) : [];\n      for (_i = 0, _len = objects.length; _i < _len; _i++) {\n        object = objects[_i];\n        for (name in object) {\n          if (!target.hasOwnProperty(name)) {\n            target[name] = object[name];\n          }\n        }\n      }\n      return target;\n    },\n    extend: function() {\n      var name, source, sources, target, _i, _len;\n      target = arguments[0], sources = 2 <= arguments.length ? __slice.call(arguments, 1) : [];\n      for (_i = 0, _len = sources.length; _i < _len; _i++) {\n        source = sources[_i];\n        for (name in source) {\n          target[name] = source[name];\n        }\n      }\n      return target;\n    }\n  };\n\n}).call(this);\n",
      "type": "blob"
    },
    "pixie": {
      "path": "pixie",
      "content": "module.exports = {\"version\":\"0.1.0\"};",
      "type": "blob"
    }
  },
  "progenitor": {
    "url": "http://strd6.github.io/editor/"
  },
  "version": "0.1.0",
  "entryPoint": "main",
  "repository": {
    "id": 18501018,
    "name": "util",
    "full_name": "distri/util",
    "owner": {
      "login": "distri",
      "id": 6005125,
      "avatar_url": "https://avatars.githubusercontent.com/u/6005125?",
      "gravatar_id": "192f3f168409e79c42107f081139d9f3",
      "url": "https://api.github.com/users/distri",
      "html_url": "https://github.com/distri",
      "followers_url": "https://api.github.com/users/distri/followers",
      "following_url": "https://api.github.com/users/distri/following{/other_user}",
      "gists_url": "https://api.github.com/users/distri/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/distri/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/distri/subscriptions",
      "organizations_url": "https://api.github.com/users/distri/orgs",
      "repos_url": "https://api.github.com/users/distri/repos",
      "events_url": "https://api.github.com/users/distri/events{/privacy}",
      "received_events_url": "https://api.github.com/users/distri/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/distri/util",
    "description": "Small utility methods for JS",
    "fork": false,
    "url": "https://api.github.com/repos/distri/util",
    "forks_url": "https://api.github.com/repos/distri/util/forks",
    "keys_url": "https://api.github.com/repos/distri/util/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/distri/util/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/distri/util/teams",
    "hooks_url": "https://api.github.com/repos/distri/util/hooks",
    "issue_events_url": "https://api.github.com/repos/distri/util/issues/events{/number}",
    "events_url": "https://api.github.com/repos/distri/util/events",
    "assignees_url": "https://api.github.com/repos/distri/util/assignees{/user}",
    "branches_url": "https://api.github.com/repos/distri/util/branches{/branch}",
    "tags_url": "https://api.github.com/repos/distri/util/tags",
    "blobs_url": "https://api.github.com/repos/distri/util/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/distri/util/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/distri/util/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/distri/util/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/distri/util/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/distri/util/languages",
    "stargazers_url": "https://api.github.com/repos/distri/util/stargazers",
    "contributors_url": "https://api.github.com/repos/distri/util/contributors",
    "subscribers_url": "https://api.github.com/repos/distri/util/subscribers",
    "subscription_url": "https://api.github.com/repos/distri/util/subscription",
    "commits_url": "https://api.github.com/repos/distri/util/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/distri/util/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/distri/util/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/distri/util/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/distri/util/contents/{+path}",
    "compare_url": "https://api.github.com/repos/distri/util/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/distri/util/merges",
    "archive_url": "https://api.github.com/repos/distri/util/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/distri/util/downloads",
    "issues_url": "https://api.github.com/repos/distri/util/issues{/number}",
    "pulls_url": "https://api.github.com/repos/distri/util/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/distri/util/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/distri/util/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/distri/util/labels{/name}",
    "releases_url": "https://api.github.com/repos/distri/util/releases{/id}",
    "created_at": "2014-04-06T22:42:56Z",
    "updated_at": "2014-04-06T22:42:56Z",
    "pushed_at": "2014-04-06T22:42:56Z",
    "git_url": "git://github.com/distri/util.git",
    "ssh_url": "git@github.com:distri/util.git",
    "clone_url": "https://github.com/distri/util.git",
    "svn_url": "https://github.com/distri/util",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "master_branch": "master",
    "permissions": {
      "admin": true,
      "push": true,
      "pull": true
    },
    "organization": {
      "login": "distri",
      "id": 6005125,
      "avatar_url": "https://avatars.githubusercontent.com/u/6005125?",
      "gravatar_id": "192f3f168409e79c42107f081139d9f3",
      "url": "https://api.github.com/users/distri",
      "html_url": "https://github.com/distri",
      "followers_url": "https://api.github.com/users/distri/followers",
      "following_url": "https://api.github.com/users/distri/following{/other_user}",
      "gists_url": "https://api.github.com/users/distri/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/distri/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/distri/subscriptions",
      "organizations_url": "https://api.github.com/users/distri/orgs",
      "repos_url": "https://api.github.com/users/distri/repos",
      "events_url": "https://api.github.com/users/distri/events{/privacy}",
      "received_events_url": "https://api.github.com/users/distri/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "network_count": 0,
    "subscribers_count": 2,
    "branch": "master",
    "publishBranch": "gh-pages"
  },
  "dependencies": {}
});